### PR TITLE
Added Bunny.net CDN SVG logo

### PR DESCRIPTION
**Pull request by jasper-on-github**
# Requirements

> Go over all the following points, and put an `x` in all the boxes that apply.

- [x] My issuer icon(s) are fully vector and do not contain (parts of) a JPG/PNG/etc.
- [x] My issuer icon(s) are somewhat square, so they are nicely visible in the app.
- [x] My issuer icon(s) start and end with the `<svg>` element.
- [x] My issuer icon(s) are scalable (they use `viewBox` instead of a static width/height).
- [x] My issuer icon(s) do not contain whitespace around the SVG ([this](https://jsfiddle.net/u9x423ph/2/) JSFiddle could help to remove whitespace).
- [x] My issuer icon(s) do not include the `doctype` element.
- [x] My issuer icon(s) file and directory names are lowercase.

### CODE REVIEW

**Comment by TehPsychedelic** [comment]
Is this logo supposed to be in the root path? @tijme

**Comment by tijme** [comment]
Oh no! Just deleted it, didn't see. This should be in the unit test too 🙈

Thanks for the heads up.

**Comment by TehPsychedelic** [comment]
Okie sounds good, to include in the unit tests to avoid in the future 🙂👍🏼

**Comment by jasper-on-github** [comment]
Oops, thought I had placed it under the right path 🙈

**Pull request merged**
