### PR TITLE
Add algolia icons

### PR DESCRIPTION
**Pull request by juancarrillofl**
Nothing more to say, really. Just forgot to add these icons in my last PR 😅

### CODE REVIEW

**Comment by tijme** [comment]
Thanks for helping with the icons @juancarrillofl! 🚀

**Comment by juancarrillofl** [comment]
Thanks to you for your work! Wondering why these icons don't appear in the app after refreshing 🤔, would you know why?

**Comment by tijme** [comment]
Sorry @juancarrillofl, I forgot to update them on the server and apparently the cronjob that has to do this automatically doesn't work. Should be available in the app now though! 🚀

**Comment by juancarrillofl** [comment]
Confirming that it works, let's go. Thank you!

**Pull request merged**
