### PR TITLE
new visa logo

### PR DESCRIPTION
**Pull request by Shargass2**
# Requirements

> Go over all the following points, and put an `x` in all the boxes that apply.

- [x] My issuer icon is fully vector and does not contain (parts of) a JPG/PNG/etc.
- [x] My issuer icon contains the original brand logo, not that from an icon pack.
- [x] My issuer icon is somewhat square, so it's nicely visible in the app.
- [x] My issuer icon starts and ends with the `<svg>` element.
- [x] My issuer icon is scalable (it uses `viewBox` instead of a static width/height).
- [ ] My issuer icon does not contain whitespace around the SVG ([this](https://jsfiddle.net/u9x423ph/2/) JSFiddle could help to remove whitespace).
- [x] My issuer icon does not include the `doctype` element.
- [x] My issuer icon directory and file name is lowercase.
- [x] My issuer icon directory and file are in the `vectors/[domain name]/` folder.
- [x] My pull request contains just one icon.

### CODE REVIEW

**Comment by mcmehrtens** [comment]
@Shargass2 This PR includes two icons. Please refer to the last bullet of the [contribution requirements](https://github.com/raivo-otp/issuer-icons#Requirements):

> One logo per pull request.

**Review by mcmehrtens — CHANGES_REQUESTED** [review]
Please refer to the [contribution requirements](https://github.com/raivo-otp/issuer-icons#Requirements):

> One logo per pull request.

Please remove one logo from this pull request and create a separate pull request for the removed logo.

**Comment by Shargass2** [comment]
Sorry, it's my first time there.
Should be ok now.

**Review by mcmehrtens — APPROVED** [review]

**Comment by tijme** [comment]
I see that there's currently a lot of whitespace around the icon. Have you used the jsfiddle to remove it? Otherwise it will be very small in the app.

**Comment by Shargass2** [comment]
I used jsfiddle to remove whitespace, I hope it will be ok now :)

**Pull request merged**
