### PR TITLE
Adding basecamp + chief delphi + zoom

### PR DESCRIPTION
**Pull request by itsmichaelyu**

### CODE REVIEW

**Comment by tijme** [comment]
Hi @itsmichaelyu,

Nice pull request! Could you check the icon of chief delphi? It contains a lot of whitespace around the icon. I added a link to the README to a JSFiddle which allows you to remove the whitespace.

When fixed I can merge the request. 

Thanks!

**Comment by itsmichaelyu** [comment]
I initially forgot to run the JSFiddle, but I fixed it in the last commit. Did I not do it correctly?

**Comment by tijme** [comment]
This is how the latest commit looks for me. Highlighted the whitespace in green.

image

**Comment by itsmichaelyu** [comment]
Ok, I fixed it I think.

**Pull request merged**
