### PR TITLE
added uptime-kuma.svg

### PR DESCRIPTION
**Pull request by calvin-li-developer**
Hey,

I added uptime-kuma.svg but they dont have a website. It's a service I use to keeping track of website uptime. I named the file just uptime-kuma. I'm not sure if that's okay. Please let me know.

Thanks!

### CODE REVIEW

**Comment by calvin-li-developer** [comment]
uptime-kuma developer does not have a domain name. How do i resolve this?

**Comment by tijme** [comment]
Hmm quite an interesting use case, I have to think about this.

**Comment by tijme** [comment]
I propose that we use the `.loc` (local) TLD as a quick and dirty fix to allow this icon 😄

**Comment by calvin-li-developer** [comment]
sure, that'll work. I can change the folder name from `uptime-kuma` to `uptime-kuma.loc`

**Comment by tijme** [comment]
Sorry for letting you wait that long @calvin-li-developer!

**Comment by calvin-li-developer** [comment]
It's all good. Thanks for merging my request! 😊

**Pull request merged**
