### PR TITLE
create sendgrid.svg

### PR DESCRIPTION
**Pull request by orthanc42**
# Requirements

> Go over all the following points, and put an `x` in all the boxes that apply.

- [x] My issuer icon(s) are fully vector and do not contain (parts of) a JPG/PNG/etc.
- [x] My issuer icon(s) are somewhat square, so they are nicely visible in the app.
- [x] My issuer icon(s) start and end with the `<svg>` element.
- [x] My issuer icon(s) are scalable (they use `viewBox` instead of a static width/height).
- [x] My issuer icon(s) do not contain whitespace around the SVG ([this](https://jsfiddle.net/u9x423ph/2/) JSFiddle could help to remove whitespace).
- [x] My issuer icon(s) do not include the `doctype` element.
- [x] My issuer icon(s) file and directory names are lowercase.

### CODE REVIEW

**Comment by orthanc42** [comment]
created icon for sendgrid.

**Comment by tijme** [comment]
Can't merge as you've added the folder to the root, instead of in the `vectors/` folder. Could you update it? 

Thanks!

**Comment by orthanc42** [comment]
moved file to correct location and removed header from svg file.

**Comment by tijme** [comment]
Thanks buddy 🍻

**Pull request merged**
