### PR TITLE
Box

### PR DESCRIPTION
**Pull request by thrawartlike**

### CODE REVIEW

**Comment by thrawartlike** [comment]
Hello, @tijme! I wanted to point out the Tutanota icon doesn’t display the right nuance of red, it is rather greyish and faded inside the app. You might want to have a look. Thank you. ( I commented here so I wouldn’t have to open an issue )

**Comment by thrawartlike** [comment]
@tijme and the DROP icon has a problem inside the app. We can only see a tiny bit of the upper left corner of the icon.

**Comment by tijme** [comment]
> @tijme and the DROP icon has a problem inside the app. We can only see a tiny bit of the upper left corner of the icon.

This has been fixed now :) Please refresh again.

**Comment by tijme** [comment]
> Hello, @tijme! I wanted to point out the Tutanota icon doesn’t display the right nuance of red, it is rather greyish and faded inside the app. You might want to have a look. Thank you. ( I commented here so I wouldn’t have to open an issue )

You won't believe it, but it's actually a feature 😅 . When dark mode is enabled, all icons are made lighter by a certain percentage. This prevents that for example black icons are not visible. If you would like to have this fixed, please create an issue or a merge requests.

**Pull request merged**
