### PR TITLE
Create ruhr-uni-bochum.de

### PR DESCRIPTION
**Pull request by Schumiii**
ruhr-uni-bochum

### CODE REVIEW

**Comment by tijme** [comment]
Hi @Schumiii,

I can't merge this icon as it does not meet the requirements stated in the README.

**Comment by Schumiii** [comment]
That's very odd because I can view the svg without any problems and I removed the height/width information within the SVG file.
This is my first contribution on GitHub. May you explain what I'd need to change in order to make this work?

**Comment by Schumiii** [comment]
ruhr-uni-bochum

**Comment by Schumiii** [comment]
I uploaded the edited version again. In this conversation the logo is visible but once I try to open the image in another tab/window it's pure black...

**Comment by tijme** [comment]
It needs to be compliant with the requirements, as otherwise it cannot be parsed in the app. For example, with a static width/height, the icon has an incorrect size in the app.

Currently, the icon does not comply with various requirements (the second one because the file is not in a folder with the name of the domain)
* Must be scalable (must not have static width/height attributes, use a viewBox instead).
* The file and directory name must be lowercase.

Furthermore, you are uploading the icon as a comment instead of in the source of this repo.

**Comment by Schumiii** [comment]
Thanks for the explanation. I removed the static width/height tags within the SVG file - only viewBox is included so it should work now.
I never created a folder or anything on GitHub before. How do I do it and how would I correctly upload the SVG file with the right name?

I'd really like to contribute to this project but I am still learning how to use this page. I'm sorry.

**Comment by tijme** [comment]
Unfortunately I cannot help everyone with icons and making pull requests, due to limit availability/capacity. I recommend closing this pull request and creating a new one. The icon should be in a folder called the domain name, in de vectors folder. The icon itself should meet the requirements stated in the README.md file.

**Comment by Schumiii** [comment]
@tijme Understood. I'll try to figure it out and post it again. Thanks anyways for your help and advice!

**Pull request closed without merging**
