### PR TITLE
Added Altaro, Ansys, Autotask, Datto Portal, Datto RMM, Hudu, Huntress, Pax8, and Quickpass Icons

### PR DESCRIPTION
**Pull request by hsquaredinfotech**
# Requirements

> Go over all the following points, and put an `x` in all the boxes that apply.

- [X] My issuer icon(s) are fully vector and do not contain (parts of) a JPG/PNG/etc.
- [X] My issuer icon(s) are somewhat square, so they are nicely visible in the app.
- [X] My issuer icon(s) start and end with the `<svg>` element.
- [X] My issuer icon(s) are scalable (they use `viewBox` instead of a static width/height).
- [X] My issuer icon(s) do not contain whitespace around the SVG ([this](https://jsfiddle.net/u9x423ph/2/) JSFiddle could help to remove whitespace).
- [X] My issuer icon(s) do not include the `doctype` element.
- [X] My issuer icon(s) directory and file names are lowercase.
- [X] My issuer icon(s) directory and file are in the `vectors/` folder.

### CODE REVIEW

**Comment by tijme** [comment]
You committed files with names like `vectors/sfgnsdfgxdfgbndfgbndfgb/com fuck you/__init__.py`. Please remove those.

**Comment by tijme** [comment]
Furthermore, there are a lot of icons that you updated, but haven't changed. For example `vectors/salesforce.com/salesforce.svg`. That file contains 28 changes according to GitHub, but I could you elaborate on what is improved in icons like these?

**Comment by tijme** [comment]
I see that only a few icons were actually added.

**Comment by hsquaredinfotech** [comment]
Yeah something got messed up. No idea what that folder is and i didn't edit anything else at all. Not sure why it shows 28 changes to salesforce, could be from the initial commit getting messed up and removing all of the folders so i had to re-add them. Just close this one out and I will make a new, clean commit.

**Pull request closed without merging**
