### PR TITLE
Mailchimp, Upcloud, Warframe, Zoom, pcloud, SpiderOak, Fanatical, Wirex, Gate.io, Gemini, Huobi, Poloniex, Liquid, Cex.io, Bitso, BKEX, HitBTC, OKex, BitForex, YObit, Bit-Z + 2 extra IFTTT icons + 2 extra Kraken icons + 1 extra UBER icon + 1 extra Ubisoft icon +1 extra Keybase icon

### PR DESCRIPTION
**Pull request by thrawartlike**

### CODE REVIEW

**Comment by tijme** [comment]
Hey @thrawartlike 

Wow, thats a huge merge request! Thanks for adding all these icons.

Just a heads up about the vectors. In some other merge requests I noticed that not all SVGs are resizable, and some contain whitespace around the icon. Icons with whitespace around them will eventually show up a lot smaller in the app. When they have a fixed width or height they will be either very small or very large. All in all this makes them unusable in Raivo OTP.

I updated the SVG [requirements](https://github.com/raivo-otp/issuer-icons#svg-requirements) a bit. The following requirements have been added.

* must be scalable (must not have a static width/height)
* must not have whitespace around the SVG (use [this](https://jsfiddle.net/hbcdroey/1/) JSFiddle to remove the whitespace)
* must be a vector (do not embed a PNG inside an SVG)
* file and directory name must be lowercase without spaces (use dashes instead)

When complying with these requirements we are sure that the icons will work and show up beautifully in Raivo OTP. I just updated the `validate.py` script to make sure all these requirements must be met (otherwise TravisCI will fail).

Would you mind updating this merge requests (or creating a new one)?

Thanks,
Tijme

**Comment by thrawartlike** [comment]
The update will be done in aprox. 2 hours. Thank you.

**Comment by thrawartlike** [comment]
Done @tijme

**Comment by thrawartlike** [comment]
How do I make them scalable? I’ve only used JSFiddle and it seems like all of my icons’ aspect ratio are not right. Do you have a script that does it automatically or something? Because I see that all of my svgs’ code are way different after you fix them.

**Comment by tijme** [comment]
Hey @thrawartlike, seems like I was able to fix most of the aspect ratios.

What I do normally is this;
* First I look online (Google) if the website has some original SVG logo's somewhere. If there are any, I use those.
* If there are none to be found online, I try websites such as https://worldvectorlogo.com/.
* The last resort is https://www.vectorizer.io/, however, most of the time the output of that website does not meet quality standards.

How did you gather all these SVGs? Maybe I can give you some other tips.

**Comment by tijme** [comment]
Anyhow, I've merged the first batch of icons! 🚀 

Thanks a lot for all the effort you're putting into this.

**Comment by thrawartlike** [comment]
I mostly googled the company’s name + the word ‘logo’, found the image, imported it into adobe illustrator, image traced it, ungrouped it, deleted unnecessary layers + background then exported it and used the JSFiddle.

**Comment by tijme** [comment]
> I mostly googled the company’s name + the word ‘logo’, found the image, imported it into adobe illustrator, image traced it, ungrouped it, deleted unnecessary layers + background then exported it and used the JSFiddle.

Hmm, I'm not sure why it's going wrong with the aspect ratio then. I haven't used Adobe Illustrator myself.

Maybe it helps if you search on Google for example on `apple logo filetype:svg`, so that you don't have to convert PNGs or JPEGs to vectors. I think that will prevent the strange aspect ratios and blurry edges.

**Comment by thrawartlike** [comment]
I've tested vectorized and searched through world vector logo but all of the files seem to have a fixed width and height. Do you run them through something else? So they can adjust themselves automatically? For ex: I searched on world vector for the mailchimp svg, found it, opened it and found them to have fixed width and height "width="512px" height="512px" viewBox="0 0 5120 5120" preserveAspectRatio="xMidYMid meet">". How do I adjust this?

**Comment by thrawartlike** [comment]
The result from the previous comment was on the file used on VECTORIZER.IO and this is what lies within the svg downloaded straight from world vectorizer "viewBox="0 0 232.1 250.3" width="2318" height="2500">"

**Comment by tijme** [comment]
Ah, good point! I actually did the same for the MailChimp icon.

So what I do. I convert `width="512px" height="512px" viewBox="0 0 512 512"` to `viewBox="0 0 512 512"`. If there's any whitespace left, than I throw the SVG in the JSFiddle script.

**Comment by thrawartlike** [comment]
Gate.io and Cex.io are not showing up in the app @tijme

**Comment by tijme** [comment]
I think you found a bug. Somehow directory names with dots inside them don't show up in the app. I've renamed them for now.

If you refresh the icons you'll be able to see them!

I'll fix this weird issue later :)

**Comment by thrawartlike** [comment]
Yep. They show up now.

**Pull request merged**
