### PR TITLE
feat: add snapshooter.com

### PR DESCRIPTION
**Pull request by juancaorg**
Not perfect, but I think it could work fine for now.

### CODE REVIEW

**Comment by tijme** [comment]
@juancaorg could it be that this is a PNG/JPG converted to vector? It looks vary pixelated.

**Comment by juancaorg** [comment]
Yeah :( couldn't find an SVG of the logo. Let me contact the owner of the service to try to get the SVG. 

I'll update this PR later with a better logo.

**Comment by juancaorg** [comment]
@tijme Now it's fixed! Shoutout to the founder which provided the icons himself :)

**Comment by mrsimonbennett** [comment]
Thanks @tijme and @juancaorg greatly appreciated :)

**Pull request merged**
