### PR TITLE
added round versions of ui.com/crypto.com/gov.uk/cex.io/cloudflare/epic games/ftx/kickstarter

### PR DESCRIPTION
**Pull request by walderston**

### CODE REVIEW

**Comment by tijme** [comment]
Hi @walderston, are these official brand logo's or did you get them from a third party? They all look like they're the same style, while it should be the official brand logo.

**Comment by walderston** [comment]
@tijme they are the official logo just in a round circle. 

If that's not okay, let me know and I'll close the PR.

**Comment by tijme** [comment]
I can understand that you may have put a lot of work into this pull request, so it sucks to close it. But I feel like the repo should primarily consist of the official logo's according to the official branding guidelines. I try to adhere to that as much as possible.

**Comment by walderston** [comment]
It's all good. Just wanted to try and make the icons uniform (but OCD like that). Closed PR. Thanks

**Pull request closed without merging**
