### PR TITLE
Add crypto.com

### PR DESCRIPTION
**Pull request by remygillet**

### CODE REVIEW

**Comment by tijme** [comment]
Hello Remy, 

Just wanted to let you know that the icon must comply with the requirements (https://github.com/raivo-otp/issuer-icons#svg-requirements) and should pass the tests.

**Comment by remygillet** [comment]
Remove static attributes

**Comment by tijme** [comment]
I updated it a bit. Please see this commit for the changes that were required: https://github.com/raivo-otp/issuer-icons/pull/281/commits/88f902d80ae76e61eed5ffc1f061a434f9939204

**Comment by remygillet** [comment]
Thank you so much, i keep in mind the 88f902d commit :)

**Pull request merged**
