### PR TITLE
Synology - Home Assistant icons

### PR DESCRIPTION
**Pull request by benzo83**

### CODE REVIEW

**Comment by tijme** [comment]
Hey @benzo83,

I'm sorry, I totally missed your pull request. I would like to merge it, but just wondering why you've deleted SimpleLogin?

**Comment by benzo83** [comment]
Don't worry, however I removed the simplelogin icon as it is already present in the repo.

**Comment by tijme** [comment]
Please correct me if I'm wrong; I'm not seeing the SimpleLogin in the master that you're trying to merge (https://github.com/benzo83/issuer-icons/tree/master/vectors), and I see the simplelogin folder+files have been deleted in your commit. This would mean that on merge, it would also be deleted in the Raivo OTP issuer icons master branch.

**Comment by benzo83** [comment]
I'm new to github, so I'm not sure how to proceed. Obviously I intended to keep the previously created icon. How to procede now?  I am really embarrassed :/

**Comment by tijme** [comment]
Oh don't worry about it! I'll fix it tomorrow by adding the icon again and merging your merge request. I'll notify you when done!

**Comment by benzo83** [comment]
Thank you 🙏

**Pull request merged**
